name: "effx sync"
description: "Sync data to effx with config files."
inputs:
  directory:
    description: "Directory for effx config files."
    required: true
runs:
  using: "composite"
  steps:
    - name: Download CLI
      shell: bash
      run: |
        curl -Lo __effx_cli https://effx.run/effx-cli/releases/latest/effx-cli_Linux_x86_64
        sudo install __effx_cli /usr/local/bin
    - name: Sync all Effx Yaml files
      shell: bash
      run: __effx_cli sync -d ${{ inputs.directory }}
