name: Sync effx
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Sync effx configuration with effx account
        uses: effxhq/effx-sync-action@master
        with:
          directory: ${{ github.workspace }}
        env:
          EFFX_API_KEY: ${{ secrets.EFFX_API_KEY }}
